export const iconStyles = {
  width: 24,
  height: 24,
  fill: "#FEFEFE",
};

export const ITEMS = [
  {
    id: "item01",
    name: "T-shirt",
    price: 19.99,
    category: "clothing",
    qtyAvailable: 20,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["red", "white", "black"],
      size: ["S", "M", "L"],
    },
  },
  {
    id: "item02",
    name: "Shoes",
    price: 42.15,
    category: "shoes",
    qtyAvailable: 42,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black"],
      size: ["M", "L"],
    },
  },
  {
    id: "item03",
    name: "Hat",
    price: 9.0,
    category: "hats",
    qtyAvailable: 22,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["red", "white", "black", "pink", "yellow"],
      size: ["S", "M", "L"],
    },
  },
  {
    id: "item04",
    name: "Clock",
    price: 125.99,
    category: "accessories",
    qtyAvailable: 7,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["golden", "black"],
      size: ["S", "M", "L"],
    },
  },
  {
    id: "item05",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item06",
    name: "Converse All-star",
    price: 36.0,
    category: "shoes",
    qtyAvailable: 65,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "Black"],
      size: ["S", "M", "L", "XL"],
    },
  },
  {
    id: "item07",
    name: "Pendant",
    price: 125.0,
    category: "accessories",
    qtyAvailable: 74,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["White"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item08",
    name: "Earrings",
    price: 9.99,
    category: "accessories",
    qtyAvailable: 12,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item09",
    name: "Bikini",
    price: 19.0,
    category: "clothing",
    qtyAvailable: 152,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      size: ["S", "M", "L"],
    },
  },
  {
    id: "item10",
    name: "Jumper",
    price: 102.0,
    category: "clothing",
    qtyAvailable: 14,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      size: ["S", "M", "L"],
    },
  },
  {
    id: "item11",
    name: "Sneakers",
    price: 31.0,
    category: "shoes",
    qtyAvailable: 65,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      size: ["S", "M", "L"],
    },
  },
  {
    id: "item12",
    name: "Socks",
    price: 5.0,
    category: "accessories",
    qtyAvailable: 213,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      size: ["S", "M", "L"],
    },
  },
  {
    id: "item13",
    name: "Skirt",
    price: 49.99,
    category: "clothing",
    qtyAvailable: 52,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      size: ["S", "M", "L"],
    },
  },
  {
    id: "item14",
    name: "Polo T-shirt",
    price: 65.0,
    category: "clothing",
    qtyAvailable: 53,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      size: ["S", "M", "L"],
    },
  },
  {
    id: "item15",
    name: "High Heels",
    price: 39.0,
    category: "shoes",
    qtyAvailable: 12,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      size: ["S", "M", "L"],
    },
  },
  {
    id: "item16",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      size: ["S", "M", "L"],
    },
  },
  {
    id: "item17",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      size: ["XS", "S", "M", "L"],
    },
  },
  {
    id: "item18",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item19",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item20",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item21",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item22",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item23",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item24",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item25",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item26",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item27",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item28",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item29",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item30",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item31",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item32",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item33",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item34",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item35",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item36",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item37",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item38",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item39",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item40",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item41",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item42",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item43",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item44",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item45",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item46",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item47",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item48",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item49",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item50",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item51",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item52",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item53",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item54",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item55",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item56",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item57",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item58",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item59",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item60",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item61",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item62",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item63",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item64",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
  {
    id: "item6",
    name: "Bag",
    price: 12.0,
    category: "accessories",
    qtyAvailable: 109,
    quantity: 1,
    imageSrc: "/",
    additionalInfo: {
      colors: ["white", "black", "yellow"],
      // size: ["S", "M", "L"],
    },
  },
];
